# -*- coding: utf-8 -*-
"""intern projectipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15x6ZyaWyToobF5qzwIQadp4fnifcKlzA
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
!pip install bioinfokit

df=pd.read_csv('mcdonalds.csv')

df.tail()

df.info()

df.shape

def dataoveriew(df, message):
    print(f'{message}:\n')
    print('Number of rows: ', df.shape[0])
    print("\nNumber of features:", df.shape[1])
    print("\nData Features:")
    print(df.columns.tolist())
    print("\nMissing values:", df.isnull().sum().values.sum())
    print("\nUnique values:")
    print(df.nunique())
    
dataoveriew(df, 'Overview of the dataset')

df['Like'].replace(['I hate it!-5','I love it! +5'],
                        [-5,+5], inplace=True)

df

df['disgusting'].replace(['No','Yes'],
                        [0,1], inplace=True)

sns.pairplot(df,hue="disgusting")
# to show
plt.show()

sns.pairplot(df,hue="Like")
# to show
plt.show()



df.describe().T

df.Age.value_counts().plot.pie()

df['VisitFrequency'].replace(['Never','Once a year','Every three months', 'Once a month','Once a week','More than once a week'],
                        [-2,-1,0, 1,2,3], inplace=True)

df

#df['cheap	'].replace(['No','Yes'],
                        #[0,1],inplace=True)
df['tasty'].replace(['No','Yes'],
                        [0,1], inplace=True)
df['spicy'].replace(['No','Yes'],
                        [0,1], inplace=True)
df['healthy'].replace(['No','Yes'],
                        [0,1], inplace=True)
df['expensive'].replace(['No','Yes'],
                        [0,1], inplace=True)
df['convenient'].replace(['No','Yes'],
                        [0,1], inplace=True)

df

print(df.corr())
  
# plotting correlation heatmap
dataplot = sns.heatmap(df.corr(), cmap="YlGnBu", annot=True)
  
# displaying heatmap
plt.Figure

df.groupby('disgusting').plot()

